### PR TITLE
Migrate to nullsafety and clean up linting problems

### PR DESCRIPTION
**Pull request by productiveme**

### CODE REVIEW

**Review by luanpotter — APPROVED** [review]
LGTM

**Comment by thosakwe** [comment]
Thanks for the PR. Been a while since I've done anything with Pub - should the new version be `2.0.0`, or is `1.4.0` fine?

**Comment by rrousselGit** [comment]
This should be 2.0.0

**Comment by thosakwe** [comment]
Thanks once again. Version 2.0.0: https://pub.dev/packages/prompts/versions/2.0.0

**Pull request merged**
